### ISSUE TITLE
Pets & Piglins

### ISSUE THREAD

**Issue by AlexPotato115** [Tfarcenim/FunctionalArmorTrim#3]
I've tested the mod a little bit, as it seemed like something that should have been in the 1.20 update, and I've noticed 2 things.

1. Pets (Wolves are what I've tested with) seem to take damage from mobs as if the mobs had thorns. The mobs don't directly attack or damage the pets, but the pets take damage whenever they land a hit on the mob. I have verified that this mod is the culprit for that behavior.
2. Piglins do not become neutral when armor has a gold trim on it. They don't seem to care or notice.

**Comment by Tfarcenim** [comment]
fixed
