### ISSUE TITLE
[1.20.1-Forge] Crash when reloading / switching resource pack.

### ISSUE THREAD

**Issue by Gbergz** [Tfarcenim/FunctionalArmorTrim#4]
## What happened: 
Crash when reloading / switching resource pack.

## Versions:
MC: 1.20.1
Forge: 47.1.3
Functional Armor Trim: functionalarmortrim-1.20.1-2.jar

## Crash-Report:
https://gist.githubusercontent.com/Gbergz/3f70a8d5e5b326c7240843f28cc05986/raw/5b866dcf7e47e5abb094063d55dfd1d6f870443e/gistfile1.txt

**Comment by Tfarcenim** [comment]
Fixed in 2.1
