### ISSUE TITLE
[Suggestion?] Why netherite trim doesn't give additional armor and toughness?

### ISSUE THREAD

**Issue by chemlzh** [Tfarcenim/FunctionalArmorTrim#7]
Armor improvement based on trim material is a good idea, and I love it so much. However, I found that iron trim can give armor, diamond trim can give armor and toughness, while netherite trim ... just gives fireproof and fire resistance? I use an expensive material usually for advanced armors, and at last I just attain these two buffs without armor and toughness improvement. Do you think it's too expensive for this sacrifice? I hope netherite trim can also give armor and toughness like diamonds, otherwise I will feel it's not a great deal to use netherite for armor trims.

**Comment by Tfarcenim** [comment]
Added
