### ISSUE TITLE
NeoForge: Opening chests with mod installed causes game to freeze and crash.

### ISSUE THREAD

**Issue by CsillaAria** [Tfarcenim/FunctionalArmorTrim#8]
NeoForge version 21.0.78

Mod version: functionalarmortrim-neoforge-1.21-0.jar

This is the latest crash log I had to use task manager to close the game after it locked up the game: https://bytebin.lucko.me/8cSJphHL95

I think this is the crash log from when it actually crashed the first time: https://bytebin.lucko.me/b1ZcSJjlb0

**Comment by Tfarcenim** [comment]
fixed in 1.21-1

**Comment by CsillaAria** [comment]
Wow that was so fast. Thank you!
