### ISSUE TITLE
Game crashing on world creation

### ISSUE THREAD

**Issue by jaredinyaagha1** [Tfarcenim/FunctionalArmorTrim#9]
Hey I noticed that the game seems to come up with an error whenever I have this mod turned on in my current custom modpack set up.

The game sends this error message upon crash: 

The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: Cannot read field "f46443" because "level" is null

Here's the crash log: https://pastebin.com/xhWwKhMM

Thanks!

**Comment by Tfarcenim** [comment]
Have you tested with no other mods?

**Comment by jaredinyaagha1** [comment]
I noticed it seems to come up when Quark or Spell Power Attributes (a mod required for Spell Engine to run) are installed but when I do not have Functional Armor Trims installed it runs okay even when both of those two are installed.

**Comment by Tfarcenim** [comment]
I blame the other mods trying to load items too early.

**Comment by Tfarcenim** [comment]
Wait a minute, spell engine is a fabric mod, and this is a forge instance.  That means this is not my fault and you should talk to the connector guys about it.  No further action will be done on my end.

**Comment by jaredinyaagha1** [comment]
Okay, thanks for the help!
